# Generated by Django 4.2.7 on 2023-11-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegramchat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
